std_msgs/Header header
float32 quaternion_x
float32 quaternion_y
float32 quaternion_z
float32 quaternion_w

float32 acceleration_x
float32 acceleration_y
float32 acceleration_z

float32 gyro_x
float32 gyro_y
float32 gyro_z

float32 euler_x
float32 euler_y
float32 euler_z

float32 accelerometer_x
float32 accelerometer_y
float32 accelerometer_z

float32 magnetometer_x
float32 magnetometer_y
float32 magnetometer_z

float32 gravity_x
float32 gravity_y
float32 gravity_z

int32 cal_system
int32 cal_gyroscope
int32 cal_accelerometer
int32 cal_magnetometer
int32 source